## VALORES COMUNES ##
log4j.rootLogger=DEBUG, debugLog
log4j.appender.debugLog.Threshold=INFO
log4j.appender.debugLog.layout=org.apache.log4j.PatternLayout
log4j.appender.debugLog.layout.ConversionPattern=[%d{dd/MM/yyyy HH:mm:ss}] [%-1p] [%t] [CLASE:%-15.15c{1}] [METODO:%M]:"%m";%n
## POR ARCHIVO ##
log4j.appender.debugLog=org.apache.log4j.ConsoleAppender
log4j.appender.debugLog.File=/var/opt/tomcat/webapps/fasdem/log/fasdem.log
log4j.appender.debugLog.Append=true
log4j.appender.debugLog.MaxFileSize=10Mb
log4j.appender.debugLog.MaxBackupIndex=3
## POR CONSOLA ##
#log4j.appender.debugLog=org.apache.log4j.ConsoleAppender
