/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2013-10-28 22:56:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.administrador.proveedores;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ve.gob.dem.framework.recursos.*;
import java.util.Date;
import java.text.NumberFormat;
import java.util.ArrayList;
import ve.gob.dem.fasdem.bean.*;
import java.text.SimpleDateFormat;

public final class modificarProveedor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tlds/struts-bean.tld", Long.valueOf(1373379230000L));
    _jspx_dependants.put("/WEB-INF/tlds/struts-tiles.tld", Long.valueOf(1373379230000L));
    _jspx_dependants.put("/WEB-INF/tlds/fmt.tld", Long.valueOf(1373379230000L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1373379230000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  tiles:insert
      org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f0 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.get(org.apache.struts.taglib.tiles.InsertTag.class);
      _jspx_th_tiles_005finsert_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsert_005f0.setParent(null);
      // /jsp/administrador/proveedores/modificarProveedor.jsp(6,0) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsert_005f0.setPage("/jsp/plantilla/plantilla.jsp");
      int _jspx_eval_tiles_005finsert_005f0 = _jspx_th_tiles_005finsert_005f0.doStartTag();
      if (_jspx_eval_tiles_005finsert_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");



		String primera = (String)request.getAttribute("primera");
		ArrayList listaProveedores = (ArrayList) request.getAttribute("listProveedores");
		Clinica pro;
		ArrayList listaEstado = (ArrayList) request.getAttribute("listaEstado");
		Estado estado;
		ArrayList listaTipoProveedor = (ArrayList) request.getAttribute("listaTipoProveedor");
		TipoProveedor tipoProveedor;
		
		ArrayList listTipoTra = (ArrayList) request.getAttribute("listTipoTra");
		ArrayList listTipoTraPort = (ArrayList) request.getAttribute("listTipoTraPort");

		ArrayList listaTipoTramite = (ArrayList) request.getAttribute("listaTipoTramite");
		ArrayList listaTipoTramitePortal = (ArrayList) request.getAttribute("listaTipoTramitePortal");

		TipoTramite tipoTramite;
		boolean is_razonable= (Boolean)request.getAttribute("razonable");

		int est = (Integer)request.getAttribute("estado");
		int ciud = (Integer)request.getAttribute("ciudad");
		boolean is_activo= (Boolean)request.getAttribute("activo");
		ArrayList listaCiudad = (ArrayList) request.getAttribute("listaCiudad");
		Ciudad ciudad;

		

          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t");
          if (_jspx_meth_tiles_005fput_005f0(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t");
          if (_jspx_meth_tiles_005fput_005f1(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_tiles_005fput_005f2(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_tiles_005fput_005f3(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write('\r');
          out.write('\n');
          out.write('	');
          //  tiles:put
          org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f4 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.get(org.apache.struts.taglib.tiles.PutTag.class);
          _jspx_th_tiles_005fput_005f4.setPageContext(_jspx_page_context);
          _jspx_th_tiles_005fput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
          // /jsp/administrador/proveedores/modificarProveedor.jsp(47,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_tiles_005fput_005f4.setName("cuerpo");
          // /jsp/administrador/proveedores/modificarProveedor.jsp(47,1) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_tiles_005fput_005f4.setDirect("true");
          int _jspx_eval_tiles_005fput_005f4 = _jspx_th_tiles_005fput_005f4.doStartTag();
          if (_jspx_eval_tiles_005fput_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_tiles_005fput_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_tiles_005fput_005f4.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_tiles_005fput_005f4.doInitBody();
            }
            do {
              out.write("\r\n");
              out.write("\t<div style=\"overflow: visible\"></div>\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t<div style=\"overflow: visible\">\r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">RIF:</div>\r\n");
              out.write("                \t\t\t\t<div class=\"parametro titulo \">");
              out.print(request.getAttribute("rif"));
              out.write("\r\n");
              out.write("\t\t\t\t                 <input id=\"accionProveedor\" type=\"hidden\" name=\"accionProveedor\" value=");
              out.print(request.getAttribute("rif"));
              out.write(">\r\n");
              out.write("\t\t\t\t                  </div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Descripci&oacute;n:</div>\r\n");
              out.write("                \t\t\t\t<div class=\"parametro titulo \">\r\n");
              out.write("\t\t\t\t                  ");
if(request.getAttribute("descripcion")!=null || "".equals(request.getAttribute("descripcion"))){
              out.write("\r\n");
              out.write("\t\t\t\t                    <input type=\"text\" id=\"descripcion\" name=\"descripcion\" value=\"");
              out.print(request.getAttribute("descripcion"));
              out.write("\"  >\r\n");
              out.write("\t\t\t\t                  ");
}else{
              out.write("\r\n");
              out.write("\t\t\t\t                  \t<input type=\"text\" id=\"descripcion\" name=\"descripcion\" value=\"\"  >\r\n");
              out.write("\t\t\t\t                  ");
}
              out.write("\r\n");
              out.write("\t\t\t\t                  </div>\r\n");
              out.write("                                  \r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Direcci&oacute;n:</div>\r\n");
              out.write("                \t\t\t\t<div class=\"parametro titulo \">\r\n");
              out.write("\t\t\t\t                  ");
if(request.getAttribute("direccion")!=null || "".equals(request.getAttribute("direccion"))){
              out.write("\r\n");
              out.write("                                  <textarea name=\"direccion\" cols=\"70\" rows=\"2\" id=\"direccion\">");
              out.print(request.getAttribute("direccion"));
              out.write("</textarea>\r\n");
              out.write("\t\t\t                    ");
}else{
              out.write("\r\n");
              out.write("                                <textarea name=\"direccion\" cols=\"70\" rows=\"2\" id=\"direccion\"></textarea>\r\n");
              out.write("\t\t\t\t                  ");
}
              out.write("\r\n");
              out.write("\t\t\t\t                  </div>\r\n");
              out.write("                                  \r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Telefono:</div>\r\n");
              out.write("                \t\t\t\t<div class=\"parametro titulo \">\r\n");
              out.write("\t\t\t\t                  ");
if(request.getAttribute("telefono")!=null || "".equals(request.getAttribute("telefono"))){
              out.write("\r\n");
              out.write("\t\t\t\t                    <input name=\"telefono\" type=\"text\" id=\"telefono\" value=\"");
              out.print(request.getAttribute("telefono"));
              out.write("\" size=\"50\"  >\r\n");
              out.write("\t\t\t                    ");
}else{
              out.write("\r\n");
              out.write("\t\t\t\t                  \t<input name=\"telefono\" type=\"text\" id=\"telefono\" value=\"\" size=\"50\"  >\r\n");
              out.write("\t\t\t\t                  ");
}
              out.write("\r\n");
              out.write("\t\t\t\t                  </div>\r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Persona Contacto:</div>\r\n");
              out.write("                \t\t\t\t<div class=\"parametro titulo \">\r\n");
              out.write("\t\t\t\t                  ");
if(request.getAttribute("contacto")!=null || "".equals(request.getAttribute("contacto"))){
              out.write("\r\n");
              out.write("\t\t\t\t                    <input name=\"contacto\" type=\"text\" id=\"contacto\" value=\"");
              out.print(request.getAttribute("contacto"));
              out.write("\" size=\"50\"  >\r\n");
              out.write("\t                        ");
}else{
              out.write("\r\n");
              out.write("\t\t\t\t                  \t<input name=\"contacto\" type=\"text\" id=\"contacto\" value=\"\" size=\"50\"  >\r\n");
              out.write("\t\t\t\t                  ");
}
              out.write("\r\n");
              out.write("\t\t\t\t                  </div>\r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Estado:</div>\r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo cgp\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<select name=\"estado\" id=\"estado\"  class=\"cgp\"  onchange=\"irCuidad('");
              out.print(request.getAttribute("id_proveedor"));
              out.write("');\">\r\n");
              out.write("\t\t\t\t    <option value=\"-1\" selected=\"selected\" class=\"seleccione\">[SELECCIONAR]</option>\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t ");

							for (int k=0;k!=listaEstado.size();k++){
							estado = (Estado) listaEstado.get(k);
							
			      		 
              out.write("\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t<option \r\n");
              out.write("\t\t\t\t\t\t\t\t");
if(est == estado.getId()){
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\tselected=\"selected\"\r\n");
              out.write("\t\t\t\t\t\t\t\t");
}
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\tvalue=");
              out.print(estado.getId());
              out.write('>');
              out.print(estado.getDescripcion());
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</option>\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t    ");
}
              out.write("\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t        </select>\r\n");
              out.write("\t\t        \r\n");
              out.write("\t\t        </div>\r\n");
              out.write("\t\t\t\t   \r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Ciudad:</div>\r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo cgp\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<select name=\"ciudad\" id=\"ciudad\" class=\"cgp\">\r\n");
              out.write("\t\t\t\t    <option value=\"-1\" selected=\"selected\" class=\"seleccione\">[SELECCIONAR]</option>\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t ");
if(listaCiudad!=null && listaCiudad.size()!=0){
							for (int j=0;j!=listaCiudad.size();j++){
							ciudad = (Ciudad) listaCiudad.get(j);
							
			      		 
              out.write("\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t<option \r\n");
              out.write("\t\t\t\t\t\t\t\t");
if(ciud == ciudad.getId()){
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\tselected=\"selected\"\r\n");
              out.write("\t\t\t\t\t\t\t\t");
}
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\tvalue=");
              out.print(ciudad.getId());
              out.write('>');
              out.print(ciudad.getDescripcion());
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</option>\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t    ");
}}
              out.write("\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t        </select>\r\n");
              out.write("\t\t        \r\n");
              out.write("\t\t        </div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Tipo Proveedor:</div>\r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo cgp\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<select name=\"tipoProveedor\" id=\"tipoProveedor\" class=\"cgp\">\r\n");
              out.write("\t\t\t\t    <option value=\"-1\" selected=\"selected\" class=\"seleccione\">[SELECCIONAR]</option>\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t ");

							for (int i=0;i!=listaTipoProveedor.size();i++){
								tipoProveedor = (TipoProveedor) listaTipoProveedor.get(i);
							
			      		 
              out.write("\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t<option \r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t");
 if(request.getAttribute("tipoProveedor")!=null){
									if(request.getAttribute("tipoProveedor").equals(tipoProveedor.getId())){
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\tselected=\"selected\"\r\n");
              out.write("\t\t\t\t\t\t\t\t");
}}
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\tvalue=");
              out.print(tipoProveedor.getId());
              out.write('>');
              out.print(tipoProveedor.getDescripcion());
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</option>\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t    ");
}
              out.write("\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t        </select>\r\n");
              out.write("\t\t        \r\n");
              out.write("\t\t        </div>\t\t\t\t   \r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Costo Razonable:</div>\r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo cgp\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<select name=\"razonable\" id=\"razonable\" class=\"cgp\">\r\n");
              out.write("\t\t\t\t    <option value=\"-1\" selected=\"selected\" class=\"seleccione\">[SELECCIONAR]</option>\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t");
if(is_razonable){
              out.write("\r\n");
              out.write("\t\t\t\t    <option value=\"True\" selected=\"selected\" class=\"seleccione\">Si</option>\r\n");
              out.write("\t\t\t\t    <option value=\"False\" class=\"seleccione\">No</option>\r\n");
              out.write("\t\t\t\t\t\t\t\t");
}else{
              out.write("\r\n");
              out.write("\t\t\t\t\t<option value=\"True\" class=\"seleccione\">Si</option>\r\n");
              out.write("\t\t\t\t    <option value=\"False\" selected=\"selected\" class=\"seleccione\">No</option>\r\n");
              out.write("\t\t\t\t\t\t\t\t");
}
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t    \t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t        </select>\r\n");
              out.write("\t\t        \r\n");
              out.write("\t\t        </div>\r\n");
              out.write("\t\t        \r\n");
              out.write("\t\t        \t\t\t\t\t<div class=\"etiqueta titulo cgp\">Servicios que presta:</div>\r\n");
              out.write("                \t\t\t\t<div class=\"parametro titulo \">\r\n");
              out.write("\t\t\t\t                  ");
if(request.getAttribute("servicio")!=null || "".equals(request.getAttribute("servicio"))){
              out.write("\r\n");
              out.write("                                  <textarea name=\"servicio\" cols=\"70\" rows=\"2\" id=\"servicio\">");
              out.print(request.getAttribute("servicio"));
              out.write("</textarea>\r\n");
              out.write("\t\t\t                    ");
}else{
              out.write("\r\n");
              out.write("                                <textarea name=\"servicio\" cols=\"70\" rows=\"2\" id=\"servicio\"></textarea>\r\n");
              out.write("\t\t\t\t                  ");
}
              out.write("\r\n");
              out.write("\t\t\t\t                  </div>\r\n");
              out.write("\t\t        \r\n");
              out.write("\t\t        \r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Activo:</div>\r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo cgp\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<select name=\"activo\" class=\"cgp\">\r\n");
              out.write("\t\t\t\t\t\t\t\t");
if(is_activo){
              out.write("\r\n");
              out.write("\t\t\t\t    <option value=\"True\" selected=\"selected\" class=\"seleccione\">Activo</option>\r\n");
              out.write("\t\t\t\t    <option value=\"False\" class=\"seleccione\">Inactivo</option>\r\n");
              out.write("\t\t\t\t\t\t\t\t");
}else{
              out.write("\r\n");
              out.write("\t\t\t\t\t<option value=\"True\" class=\"seleccione\">Activo</option>\r\n");
              out.write("\t\t\t\t    <option value=\"False\" selected=\"selected\" class=\"seleccione\">Inactivo</option>\r\n");
              out.write("\t\t\t\t\t\t\t\t");
}
              out.write("\r\n");
              out.write("\t\t        </select>\r\n");
              out.write("\t\t        \r\n");
              out.write("\t\t        </div>\t\t                \r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t<div class=\"etiqueta titulo cgp\">\t</div>\t\r\n");
              out.write("<div class=\"parametro titulo \">\t\t\r\n");
              out.write("\t\t\t\t<table cellpadding=\"2\" cellspacing=\"1\"\r\n");
              out.write("\t\t\t\tborder=\"0\">\t\t\r\n");
              out.write("\t\t\t\t <tr valign=\"top\" >\r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t \r\n");
              out.write("<td>\t\t\t\r\n");
 if (listaTipoTramite!=null && listaTipoTramite.size()!=0){
              out.write("\t\t\t\t\r\n");
              out.write("\t<div class=\"etiqueta titulo cgp\"></div>\r\n");
              out.write("\t<div class=\"parametro titulo cgp\">\r\n");
              out.write("\t\t<table class=\"tabla\" width=\"600\" cellpadding=\"2\" cellspacing=\"1\" border=\"0\">\t\t\r\n");
              out.write("\t\t\t<tr class=\"tituloCabecera\">\r\n");
              out.write("\t\t\t\t<td>Tipo de Tramite</td>\r\n");
              out.write("\t\t\t    <td>Seleccionar</td>\t\t\t\t\t\r\n");
              out.write("\t\t\t</tr>\r\n");
              out.write("\t  \t\t");
for (int i=0;i!=listaTipoTramite.size();i++){
				tipoTramite = (TipoTramite) listaTipoTramite.get(i);
              out.write("  \t\t\r\n");
              out.write("\t\t\t\t\t<tr class=\"item\" bgcolor=\"white\" >\r\n");
              out.write("\t\t\t\t\t\t<td>");
              out.print(tipoTramite.getDescripcion());
              out.write("</td>\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t<td align=\"center\">\r\n");
              out.write("\t\t\t\t\t\t\t<INPUT type=\"checkbox\"   value=\"");
              out.print(tipoTramite.getId());
              out.write("\" \t\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t   \t\t\t\t\t\t\t");

	   							if(listTipoTra!=null){
		   							for (int j=0;j!=listTipoTra.size();j++){
			   							if((Integer)listTipoTra.get(j)==tipoTramite.getId()){
              out.write("   \r\n");
              out.write("\t\t\t   \t\t\t\t\t\t\t\tchecked \r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t");
}
			
		   							}
	   							}
              out.write("\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\tNAME=\"listTipoTra\">\r\n");
              out.write("\t\t\t\t\t\t</td>\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t");
}
              out.write("\t\r\n");
              out.write("\t\t</table>\r\n");
}
              out.write("\r\n");
              out.write("</td>\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t<td>\r\n");
              out.write("\t\t\t ");
 if (listaTipoTramitePortal!=null && listaTipoTramitePortal.size()!=0){
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t<table class=\"tabla\"  cellpadding=\"2\" cellspacing=\"1\"\r\n");
              out.write("\t\t\t\tborder=\"0\">\t\t\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t<tr class=\"tituloCabecera\">\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td>Tipo de Servicio del Portal</td>\r\n");
              out.write("\t\t\t\t    <td>Seleccionar</td>\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
 if (listTipoTraPort!=null && listTipoTraPort.size()!=0){
              out.write("\r\n");
              out.write("\t  ");

		for (int i=0;i!=listaTipoTramitePortal.size();i++){
			tipoTramite = (TipoTramite) listaTipoTramitePortal.get(i);
      
              out.write("  \t\t\r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t <tr class=\"item\" bgcolor=\"white\" >\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t<td>");
              out.print(tipoTramite.getDescripcion());
              out.write("</td>\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t<td align=\"center\">\r\n");
              out.write("\t\t\t\t<INPUT type=\"checkbox\"   value=\"");
              out.print(tipoTramite.getId());
              out.write("\" \t\t  \r\n");
              out.write("\t   ");
for (int j=0;j!=listTipoTraPort.size();j++){
		   if((Integer)listTipoTraPort.get(j)==tipoTramite.getId()){
			   
              out.write("   checked \r\n");
              out.write("\t\t\t");
}
		
	   }
              out.write("\t\t\r\n");
              out.write("\t\t\t\tNAME=\"listTipoTraPort\"></td>\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t");
}
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\t\t");
}else{
              out.write("\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\t  ");

		for (int i=0;i!=listaTipoTramitePortal.size();i++){
			tipoTramite = (TipoTramite) listaTipoTramitePortal.get(i);
      
              out.write("  \t\t\r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t <tr class=\"item\" bgcolor=\"white\" >\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t<td>");
              out.print(tipoTramite.getDescripcion());
              out.write("</td>\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t<td align=\"center\"><INPUT type=\"checkbox\"   value=\"");
              out.print(tipoTramite.getId());
              out.write("\" NAME=\"listTipoTraPort\"></td>\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t");
}
              out.write("\t\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t");
}
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\r\n");
              out.write("</table>\r\n");
              out.write("\t\r\n");
              out.write("\t");
}
              out.write("\r\n");
              out.write("\t\r\n");
              out.write("\t</td>\r\n");
              out.write("</tr>\r\n");
              out.write("\t</table>\t\r\n");
              out.write("\t\t\r\n");
              out.write("\r\n");
              out.write("\t<input id=\"accionProveedor\" type=\"hidden\" name=\"accionProveedor\">\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\r\n");
              out.write("\t<input id=\"id_proveedor\" type=\"hidden\" name=\"id_proveedor\" value=\"");
              out.print(request.getAttribute("id_proveedor"));
              out.write("\">\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t<input id=\"modifica\" type=\"hidden\" name=\"modifica\">\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t<input id=\"rif\" type=\"hidden\" name=\"rif\" value=\"");
              out.print(request.getAttribute("rif"));
              out.write("\">\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("<script>\r\n");
              out.write("function doIt(_v) {\r\n");
              out.write("document.getElementById('accionProveedor').value=_v;\r\n");
              out.write("//document.globalActionForm.busca.value=_v;\r\n");
              out.write("}\r\n");
              out.write("</script>\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("   \t\t\t\t</div>\r\n");
              out.write("<div class=\"sp5\"></div>\r\n");
              out.write("\t\t\t\t<div align=\"right\">\r\n");
              out.write("\t\t\t\t<input class=\"boton\" value=\"aceptar\" type=\"button\"  onclick=\"ir('");
              out.print(request.getAttribute("id_proveedor"));
              out.write("');\" />\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div  align=\"center\" >\r\n");
              out.write("\t\t\t\t   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<input id=\"crea\" type=\"hidden\" name=\"crea\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t<input id=\"buscaCiudad\" type=\"hidden\" name=\"buscaCiudad\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\r\n");
              out.write("\t\t\t\r\n");
              out.write("      \r\n");
              out.write("  \r\n");
              out.write("            \r\n");
              out.write("\t");
              int evalDoAfterBody = _jspx_th_tiles_005fput_005f4.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_tiles_005fput_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_tiles_005fput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f4);
            return;
          }
          _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f4);
          out.write("\r\n");
          out.write("\t\r\n");
          int evalDoAfterBody = _jspx_th_tiles_005finsert_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tiles_005finsert_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.reuse(_jspx_th_tiles_005finsert_005f0);
        return;
      }
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.reuse(_jspx_th_tiles_005finsert_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\tfunction ir(acc){\r\n");
      out.write("\t\tif(document.getElementById('rif').value ==  \"\"){\r\n");
      out.write("\t\t\talert(\"Favor introducir RIF para realizar la operación.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("  \t\tvari = document.getElementById('rif').value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvari = vari.replace(/[-.,_]/gi, '');\r\n");
      out.write("\t\tif(vari.length !=  10){\r\n");
      out.write("\t\t\talert(\"Favor introducir un RIF de 10 caracteres.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif(document.getElementById('descripcion').value ==  \"\"){\r\n");
      out.write("\t\t\talert(\"Favor introducir una descripcion para realizar la operación.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif(document.getElementById('telefono').value ==  \"\"){\r\n");
      out.write("\t\t\talert(\"Favor introducir un telefono para realizar la operación.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(document.getElementById('estado').value ==  \"-1\"){\r\n");
      out.write("\t\t\talert(\"Favor introducir un estado para realizar la operación.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tif(document.getElementById('ciudad').value ==  \"-1\"){\r\n");
      out.write("\t\t\talert(\"Favor introducir una ciudad para realizar la operación.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.getElementById('tipoProveedor').value ==  \"-1\"){\r\n");
      out.write("\t\t\talert(\"Favor introducir un Tipo Proveedor para realizar la operación.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(document.getElementById('razonable').value ==  \"-1\"){\r\n");
      out.write("\t\t\talert(\"Favor especificar si el proveedor es de costo razonable para realizar la operación.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.getElementById('servicio').value ==  \"\"){\r\n");
      out.write("\t\t\talert(\"Favor introducir uno de los servicios que presta para realizar la operación.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tdocument.getElementById('id_proveedor').value= acc;\r\n");
      out.write("\t\tdocument.getElementById('modifica').value= '2';\r\n");
      out.write("\t\tdocument.forms[0].action = \"");
      out.print(request.getContextPath());
      out.write("/security/administradores/ModificarProveedor.do\"\r\n");
      out.write("        document.forms[0].submit();\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction ir2(acc){\r\n");
      out.write("  \t\tvari = document.getElementById('busca').value;\r\n");
      out.write("\t\tvari = vari.replace(/[-.,_]/gi, '');\r\n");
      out.write("\t\tdocument.getElementById('busca').value=vari;\r\n");
      out.write("\t\tdocument.getElementById('crea').value = '1';\r\n");
      out.write("        document.forms[0].submit();\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction irCuidad(acc){\r\n");
      out.write("\t\tif(document.getElementById('estado').value ==  \"-1\"){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById('crea').value= acc;\r\n");
      out.write("\r\n");
      out.write("\t\tdocument.getElementById('buscaCiudad').value = '1';\r\n");
      out.write("\t\tdocument.forms[0].action = \"");
      out.print(request.getContextPath());
      out.write("/security/administradores/ModificarProveedor.do\"\r\n");
      out.write("\t\tdocument.forms[0].submit();\t\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ir3(acc){\r\n");
      out.write("  \t\tvari = document.getElementById('busca').value;\r\n");
      out.write("\t\tvari = vari.replace(/[-.,_]/gi, '');\r\n");
      out.write("\t\tdocument.getElementById('busca').value=vari;\r\n");
      out.write("\t\tdocument.getElementById('modifica').value = acc;\r\n");
      out.write("        document.forms[0].submit();\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction checkedAll (frm1) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (document.forms[0].miCheck.checked){\r\n");
      out.write("\t\t\talert(document.forms[0].miCheck.checked);\r\n");
      out.write("\t\t\tdocument.forms[0].listfact.checked = true;\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.forms[0].listfact.checked = true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//checked=false;\r\n");
      out.write("\t\t//var aa= document.forms[0];\r\n");
      out.write("\r\n");
      out.write("\t\t//for (var i =0; i < aa.elements.length; i++) \r\n");
      out.write("\t\t//{\r\n");
      out.write("\t\t\t// if (aa.elements[i].checked == false)\r\n");
      out.write("\t         //{\r\n");
      out.write("\t          //checked = true\r\n");
      out.write("\t         //}\r\n");
      out.write("\t       //else\r\n");
      out.write("\t         //{\r\n");
      out.write("\t         //checked = false\r\n");
      out.write("\t         //}\r\n");
      out.write("\r\n");
      out.write("\t         \r\n");
      out.write("\t\t// aa.elements[i].checked = checked;\r\n");
      out.write("\t\t//}\r\n");
      out.write("\t      }\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t");

 String mensaje = (String) request.getAttribute("mensaje");
 if (mensaje != null){
      out.write("\r\n");
      out.write(" \t<script>\r\n");
      out.write(" \t \talert('");
      out.print(mensaje);
      out.write("');\r\n");
      out.write(" \t</script>\r\n");
      out.write(" ");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005fput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f0 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/administrador/proveedores/modificarProveedor.jsp(39,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f0.setName("titulo");
    // /jsp/administrador/proveedores/modificarProveedor.jsp(39,1) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f0.setDirect("true");
    int _jspx_eval_tiles_005fput_005f0 = _jspx_th_tiles_005fput_005f0.doStartTag();
    if (_jspx_eval_tiles_005fput_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_tiles_005fput_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_tiles_005fput_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_tiles_005fput_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t");
        if (_jspx_meth_bean_005fmessage_005f0(_jspx_th_tiles_005fput_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_tiles_005fput_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_tiles_005fput_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_tiles_005fput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f0);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fput_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fput_005f0);
    // /jsp/administrador/proveedores/modificarProveedor.jsp(40,2) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setKey("principal.titulo");
    // /jsp/administrador/proveedores/modificarProveedor.jsp(40,2) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setBundle("etiquetas");
    int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
    if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f1 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/administrador/proveedores/modificarProveedor.jsp(43,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f1.setName("titulopagina");
    // /jsp/administrador/proveedores/modificarProveedor.jsp(43,1) name = content type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f1.setContent("Administrador de Cuenta de Beneficiario");
    // /jsp/administrador/proveedores/modificarProveedor.jsp(43,1) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f1.setDirect("true");
    int _jspx_eval_tiles_005fput_005f1 = _jspx_th_tiles_005fput_005f1.doStartTag();
    if (_jspx_th_tiles_005fput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f1);
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f2 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f2.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/administrador/proveedores/modificarProveedor.jsp(45,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f2.setName("itemsup");
    // /jsp/administrador/proveedores/modificarProveedor.jsp(45,1) name = content type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f2.setContent("/jsp/comunes/items.jsp");
    int _jspx_eval_tiles_005fput_005f2 = _jspx_th_tiles_005fput_005f2.doStartTag();
    if (_jspx_th_tiles_005fput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f2);
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f3 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f3.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/administrador/proveedores/modificarProveedor.jsp(46,4) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f3.setName("itemsdown");
    // /jsp/administrador/proveedores/modificarProveedor.jsp(46,4) name = content type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f3.setContent(" ");
    // /jsp/administrador/proveedores/modificarProveedor.jsp(46,4) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f3.setDirect("true");
    int _jspx_eval_tiles_005fput_005f3 = _jspx_th_tiles_005fput_005f3.doStartTag();
    if (_jspx_th_tiles_005fput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f3);
    return false;
  }
}
