/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2013-10-28 21:09:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.pago;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ve.gob.dem.framework.recursos.*;
import java.util.Date;
import java.text.NumberFormat;
import java.util.ArrayList;
import ve.gob.dem.fasdem.bean.*;
import java.text.SimpleDateFormat;

public final class fasdemMisHojaRuta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tlds/struts-bean.tld", Long.valueOf(1373379230000L));
    _jspx_dependants.put("/WEB-INF/tlds/struts-tiles.tld", Long.valueOf(1373379230000L));
    _jspx_dependants.put("/WEB-INF/tlds/fmt.tld", Long.valueOf(1373379230000L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1373379230000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  tiles:insert
      org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f0 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.get(org.apache.struts.taglib.tiles.InsertTag.class);
      _jspx_th_tiles_005finsert_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsert_005f0.setParent(null);
      // /jsp/pago/fasdemMisHojaRuta.jsp(6,0) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsert_005f0.setPage("/jsp/plantilla/plantilla.jsp");
      int _jspx_eval_tiles_005finsert_005f0 = _jspx_th_tiles_005finsert_005f0.doStartTag();
      if (_jspx_eval_tiles_005finsert_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");

		
	    ArrayList List=(ArrayList)request.getAttribute("lista");
	    String primera = (String)request.getAttribute("primera");
        HojaRuta list;
        String anio_actual = (String)request.getAttribute("a_actual");
        String mes_actual = (String)request.getAttribute("m_actual");
        
        ArrayList ListTipo=(ArrayList)request.getAttribute("tipo_hoja");
        
        TipoHojaRuta th;
        
        

	     SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
	     SimpleDateFormat formato_a = new SimpleDateFormat("yyyy");
	     NumberFormat nf = NumberFormat.getInstance();
		 nf.setGroupingUsed(true);
		 nf.setMaximumFractionDigits(2);
	 	 String dateOut;
     	 dateOut = Utilidad.DateToString(new Date(), "dd/MM/yyyy");
     

          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t");
          if (_jspx_meth_tiles_005fput_005f0(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t");
          if (_jspx_meth_tiles_005fput_005f1(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_tiles_005fput_005f2(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_tiles_005fput_005f3(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write('\r');
          out.write('\n');
          out.write('	');
          //  tiles:put
          org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f4 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.get(org.apache.struts.taglib.tiles.PutTag.class);
          _jspx_th_tiles_005fput_005f4.setPageContext(_jspx_page_context);
          _jspx_th_tiles_005fput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
          // /jsp/pago/fasdemMisHojaRuta.jsp(42,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_tiles_005fput_005f4.setName("cuerpo");
          // /jsp/pago/fasdemMisHojaRuta.jsp(42,1) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_tiles_005fput_005f4.setDirect("true");
          int _jspx_eval_tiles_005fput_005f4 = _jspx_th_tiles_005fput_005f4.doStartTag();
          if (_jspx_eval_tiles_005fput_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_tiles_005fput_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_tiles_005fput_005f4.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_tiles_005fput_005f4.doInitBody();
            }
            do {
              out.write("\r\n");
              out.write("\t<div style=\"overflow: visible\"></div>\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");

 String mensaje = (String) request.getAttribute("mensaje");
 if (mensaje != null){
              out.write("\r\n");
              out.write(" \t<script>\r\n");
              out.write(" \t \talert('");
              out.print(mensaje);
              out.write("');\r\n");
              out.write(" \t</script>\r\n");
              out.write(" ");
}

              out.write("\r\n");
              out.write("\r\n");
              out.write("\t\t        <div class=\"etiqueta titulo cgp\">Hojas de Ruta Mes:</div>\r\n");
              out.write("\t\t      \r\n");
              out.write("\t\t       \r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo \">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<select name=\"mes\" class=\"cgp\">\r\n");
              out.write("\t\t\t\t   <option value=");
              out.print("01");
              out.write(' ');
              out.print(mes_actual.equals("01")?"selected":"");
              out.write(' ');
              out.write('>');
              out.print("ENERO");
              out.write("</option>\r\n");
              out.write("\t\t\t\t   <option value=");
              out.print("02");
              out.write(' ');
              out.print(mes_actual.equals("02")?"selected":"");
              out.write('>');
              out.print("FEBRERO");
              out.write("</option>\r\n");
              out.write("\t\t\t\t    <option value=");
              out.print("03");
              out.write(' ');
              out.print(mes_actual.equals("03")?"selected":"");
              out.write('>');
              out.print("MARZO");
              out.write("</option>\r\n");
              out.write("\t\t\t\t     <option value=");
              out.print("04");
              out.write(' ');
              out.print(mes_actual.equals("04")?"selected":"");
              out.write('>');
              out.print("ABRIL");
              out.write("</option>\r\n");
              out.write("\t\t\t\t      <option value=");
              out.print("05");
              out.write(' ');
              out.print(mes_actual.equals("05")?"selected":"");
              out.write('>');
              out.print("MAYO");
              out.write("</option>\r\n");
              out.write("\t\t\t\t       <option value=");
              out.print("06");
              out.write(' ');
              out.print(mes_actual.equals("06")?"selected":"");
              out.write('>');
              out.print("JUNIO");
              out.write("</option>\r\n");
              out.write("\t\t\t\t        <option value=");
              out.print("07");
              out.write(' ');
              out.print(mes_actual.equals("07")?"selected":"");
              out.write('>');
              out.print("JULIO");
              out.write("</option>\r\n");
              out.write("\t\t\t\t         <option value=");
              out.print("08");
              out.write(' ');
              out.print(mes_actual.equals("08")?"selected":"");
              out.write('>');
              out.print("AGOSTO");
              out.write("</option>\r\n");
              out.write("\t\t\t\t          <option value=");
              out.print("09");
              out.write(' ');
              out.print(mes_actual.equals("09")?"selected":"");
              out.write('>');
              out.print("SEPTIEMBRE");
              out.write("</option>\r\n");
              out.write("\t\t\t\t           <option value=");
              out.print("10");
              out.write(' ');
              out.print(mes_actual.equals("10")?"selected":"");
              out.write('>');
              out.print("OCTUBRE");
              out.write("</option>\r\n");
              out.write("\t\t\t\t            <option value=");
              out.print("11");
              out.write(' ');
              out.print(mes_actual.equals("11")?"selected":"");
              out.write('>');
              out.print("NOVIEMBRE");
              out.write("</option>\r\n");
              out.write("\t\t\t\t             <option value=");
              out.print("12");
              out.write(' ');
              out.print(mes_actual.equals("12")?"selected":"");
              out.write('>');
              out.print("DICIEMBRE");
              out.write("</option>\r\n");
              out.write("\t\t\t\t             \r\n");
              out.write("\t\t\t    </select>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t   <div class=\"etiqueta titulo cgp\">Año:</div>\r\n");
              out.write("\t\t      \r\n");
              out.write("\t\t       \r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo \">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<select name=\"anio_h\" class=\"cgp\">\r\n");
              out.write("\t\t\t\t   ");
 int anio_act = Integer.parseInt(formato_a.format(new Date()));
				   for (int k=2011;k!=anio_act+1;k++){
              out.write("\t\t\r\n");
              out.write("\t\t\t\t\t<option title=\"");
              out.print(k);
              out.write("\" value=");
              out.print(k);
              out.write(' ');
              out.print(Integer.parseInt(anio_actual)==k?"selected":"");
              out.write('>');
              out.print(k);
              out.write("</option>\r\n");
              out.write("\t\t\t\t   ");
}
              out.write("\t\r\n");
              out.write("\t\t\t    </select>\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div class=\"sp5\"></div>\r\n");
              out.write("\t\t\t\t<div align=\"right\">\r\n");
              out.write("\t\t\t\t<input class=\"boton\" value=\"Buscar\" type=\"button\"  onclick=\"ir(1);\" />\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t<div style=\"border-bottom-color: #EEEEEE; border-bottom-width: thin; border-bottom-style: solid\">&nbsp;</div>\r\n");
              out.write("                <div style=\"border-bottom-color: #EEEEEE; border-bottom-width: thin; border-bottom-style: solid\">&nbsp;</div>\r\n");
              out.write("\t\t\t\r\n");
              out.write(" \r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Codigo de Hoja de Ruta</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo cgp\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t<input type=\"text\" name=\"codigo1\" id=\"codigo1\"  size=\"4\" value=\"\" maxlength=\"4\" class=\"cgp\"> - <input type=\"text\" name=\"codigo2\" id=\"codigo2\"  value=\"\" size=\"10\" maxlength=\"5\" class=\"cgp\"> \r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div class=\"sp5\"></div>\r\n");
              out.write("\t\t\t\t<div align=\"right\">\r\n");
              out.write("\t\t\t\t<input class=\"boton\" value=\"Buscar por codigo de Hoja\" type=\"button\"  onclick=\"ircodigo(3);\" />\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div style=\"border-bottom-color: #EEEEEE; border-bottom-width: thin; border-bottom-style: solid\">&nbsp;</div>\r\n");
              out.write("                <div style=\"border-bottom-color: #EEEEEE; border-bottom-width: thin; border-bottom-style: solid\">&nbsp;</div>\r\n");
              out.write("                <div style=\"border-bottom-color: #EEEEEE; border-bottom-width: thin; border-bottom-style: solid\">&nbsp;</div>\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Periodo Fiscal:</div>\r\n");
              out.write("\t\t      \r\n");
              out.write("\t\t       \r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo \">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<select name=\"periodo\" class=\"cgp\">\r\n");
              out.write("\t\t\t\t   ");
 int per = Integer.parseInt(formato_a.format(new Date()));
				   for (int k=2010;k!=per+2;k++){
              out.write("\t\t\r\n");
              out.write("\t\t\t\t\t<option title=\"");
              out.print(k);
              out.write("\" value=");
              out.print(k);
              out.write(' ');
              out.print(Integer.parseInt(anio_actual)==k?"selected":"");
              out.write('>');
              out.print(k);
              out.write("</option>\r\n");
              out.write("\t\t\t\t   ");
}
              out.write("\t\r\n");
              out.write("\t\t\t    </select>\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div class=\"etiqueta titulo cgp\">Tipo</div>\r\n");
              out.write("\t\t\t\t<div class=\"parametro titulo cgp\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<select name=\"tipohojar\" id=\"tipohojar\" class=\"cgp\">\r\n");
              out.write("\t\t\t\t    <option value=\"0\" selected=\"selected\" class=\"seleccione\">[SELECCIONAR]</option>\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t ");

							for (int k=0;k!=ListTipo.size();k++){
								th = (TipoHojaRuta) ListTipo.get(k);
			      		 
              out.write("\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t<option value=");
              out.print(th.getId());
              out.write('>');
              out.print(th.getDescripcion());
              out.write("</option>\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t    ");
}
              out.write("\t\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t        </select>\r\n");
              out.write("\t\t        \r\n");
              out.write("\t\t        </div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div class=\"sp5\"></div>\r\n");
              out.write("\t\t\t\t<div align=\"right\">\r\n");
              out.write("\t\t\t\t<input class=\"boton\" value=\"Crear Hoja de Ruta\" type=\"button\"  onclick=\"irCrear(4);\" />\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\t\t<div style=\"border-bottom-color: #EEEEEE; border-bottom-width: thin; border-bottom-style: solid\">&nbsp;</div>\r\n");
              out.write("                <div style=\"border-bottom-color: #EEEEEE; border-bottom-width: thin; border-bottom-style: solid\">&nbsp;</div>\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\t<table class=\"tabla\" width=\"600\" cellpadding=\"2\" cellspacing=\"1\"\r\n");
              out.write("\t\t\t\tborder=\"0\">\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t ");
 if (List!=null && List.size()!=0){
              out.write("\t\r\n");
              out.write("\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t<tr class=\"tituloCabecera\">\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td>Hoja de Ruta Nro</td>\r\n");
              out.write("\t\t\t\t\t<td>Fecha</td>\r\n");
              out.write("\t\t\t\t\t<td>Estatus</td>\r\n");
              out.write("\t\t\t\t\t<td>Tipo</td>\r\n");
              out.write("\t\t\t\t    <td>Cantidad de Pagos</td>\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t<td>Editar</td>\r\n");
              out.write("\t\t\t\t\t<td>Cerrar/Abrir</td>\r\n");
              out.write("\t\t\t\t\t<td>Reporte</td>\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\r\n");
              out.write("\t  ");

		for (int i=0;i!=List.size();i++){
		list = (HojaRuta) List.get(i);
      
              out.write("  \t\t\r\n");
              out.write("\t\t\t\t \r\n");
              out.write("\t\t\t\t <tr class=\"item\" bgcolor=\"white\" >\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t<td align=\"center\"><B>");
              out.print(list.getNumero());
              out.write("</B></td>\r\n");
              out.write("\t\t\t\t\t<input id=\"cod");
              out.print(list.getId());
              out.write("\" type=\"hidden\" name=\"cod");
              out.print(list.getId());
              out.write("\" value=\"");
              out.print(list.getFecha());
              out.write("\">\r\n");
              out.write("\t\t\t\t\t<td>");
              out.print( formato.format(list.getFecha()));
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t<td>");
              out.print(list.getStatus().getDescripcion() );
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t<td>");
              out.print(list.getTipo().getDescripcion()  );
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"center\">");
              out.print(list.getCantidad() );
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            \t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t");
if(list.getStatus().getId()==1){ 
              out.write("\r\n");
              out.write("\t\t\t\t\t\t<td class=\"grayplink\" align=\"center\"> \r\n");
              out.write("\t\t\t               <img onclick=\"irdetalle(4,'");
              out.print(list.getId());
              out.write("');\" style=\"cursor:hand\" src=\"");
              out.print(request.getContextPath());
              out.write("/images/page_add.png\" width=\"14\" height=\"13\" title=\"Agregar a Hoja de Ruta\">\r\n");
              out.write("\t\t\t            </td>\r\n");
              out.write("\t\t            ");
}else{
              out.write("\r\n");
              out.write("\t\t            \t<td align=\"center\">");
              out.print("---");
              out.write("</td>\r\n");
              out.write("\t\t            ");
}
              out.write("\r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            ");
if(list.getStatus().getId()==1){ 
              out.write("\r\n");
              out.write("\t\t\t\t\t\t<td class=\"grayplink\" align=\"center\"> \r\n");
              out.write("\t\t\t               <img onclick=\"cambiar(2,'");
              out.print(list.getId());
              out.write("','2');\" style=\"cursor:hand\" src=\"");
              out.print(request.getContextPath());
              out.write("/images/ic3d_micta.gif\" width=\"14\" height=\"13\" title=\"Cerrar\">\r\n");
              out.write("\t\t\t            </td>\r\n");
              out.write("\t\t            ");
}
              out.write("\r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            ");
if(list.getStatus().getId()==2){ 
              out.write("\r\n");
              out.write("\t\t\t\t\t\t<td class=\"grayplink\" align=\"center\"> \r\n");
              out.write("\t\t\t               <img onclick=\"cambiar(2,'");
              out.print(list.getId());
              out.write("','1');\" style=\"cursor:hand\" src=\"");
              out.print(request.getContextPath());
              out.write("/images/ic_candadoabierto.gif\" width=\"14\" height=\"13\" title=\"Abrir\">\r\n");
              out.write("\t\t\t            </td>\r\n");
              out.write("\t\t            ");
}
              out.write("\r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            ");
if(list.getStatus().getId()==3){ 
              out.write("\r\n");
              out.write("\t\t\t\t\t\t<td align=\"center\">");
              out.print("---");
              out.write("</td>\r\n");
              out.write("\t\t            ");
}
              out.write("\r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            ");
if(list.getStatus().getId()==4){ 
              out.write("\r\n");
              out.write("\t\t\t\t\t\t<td align=\"center\">");
              out.print("---");
              out.write("</td>\r\n");
              out.write("\t\t            ");
}
              out.write("\r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t             ");
if(list.getStatus().getId()==5){ 
              out.write("\r\n");
              out.write("\t\t\t\t\t\t<td align=\"center\">");
              out.print("---");
              out.write("</td>\r\n");
              out.write("\t\t            ");
}
              out.write("\r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            <td class=\"grayplink\" align=\"center\"> \r\n");
              out.write("\t\t                  <img onclick=\"javascript:openWinScroll2('");
              out.print(request.getContextPath());
              out.write("/security/pago/imprimirHojaRuta.do?h=");
              out.print(list.getId());
              out.write("','name',500,500);\" style=\"cursor:hand\" src=\"");
              out.print(request.getContextPath());
              out.write("/images/printer.png\" width=\"14\" height=\"13\" title=\"Reporte\">\r\n");
              out.write("\t\t            ");
if (list.getTipo().getId()==5){
              out.write("\r\n");
              out.write("\t                  / <img onclick=\"javascript:openWinScroll2('");
              out.print(request.getContextPath());
              out.write("/security/pago/imprimirHojaRutaXLS.do?hr=");
              out.print(list.getId());
              out.write("','name',500,500);\" style=\"cursor:hand\" src=\"");
              out.print(request.getContextPath());
              out.write("/images/excel.bmp\" width=\"14\" height=\"13\" title=\"XLS\">\r\n");
              out.write("\t                 ");
}
              out.write("\r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t            </td>\r\n");
              out.write("\t\t            \r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t");
}
              out.write("\t\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr align=\"left\">\r\n");
              out.write("\t\t\t\t\t<td align=\"left\" colspan=\"6\">\r\n");
              out.write("\t\t\t\t\t<input id=\"desde_select\" type=\"hidden\" name=\"desde_select\" value=\"");
              out.print(request.getAttribute("dselect"));
              out.write("\">\r\n");
              out.write("           \t\t\t<input id=\"hasta_select\" type=\"hidden\" name=\"hasta_select\" value=\"");
              out.print(request.getAttribute("hselect"));
              out.write("\">\r\n");
              out.write("\r\n");
              out.write("                    \r\n");
              out.write("                    \r\n");
              out.write("                    </td>\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\r\n");
              out.write("\t\r\n");
              out.write("\t");
}else{
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t");
if (primera!=null){ 
              out.write("\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t <tr>\r\n");
              out.write("\t\t\t\t\t\t<td align=\"center\" class=\"grayp\" style=\"padding-left: 20px; padding-bottom: 5px;\">\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"grayp\"></div>\r\n");
              out.write("\t\t\t\t\t\t\t<strong>No existen Hojas de Ruta</strong>\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"grayp\"></div>\r\n");
              out.write("\t\t\t\t\t\t</td>\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t");
}
              out.write(" \r\n");
              out.write("\t");
}
              out.write("    \r\n");
              out.write("\t\r\n");
              out.write("\r\n");
              out.write("\t\t\t</table>\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div  align=\"center\" >\r\n");
              out.write("\t\t\t\t   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\t\r\n");
              out.write("\r\n");
              out.write("\t\t\t<input id=\"accionPago\" type=\"hidden\" name=\"accionPago\">\r\n");
              out.write("\t\t\t<input id=\"pre\" type=\"hidden\" name=\"pre\">\r\n");
              out.write("             <input id=\"id_hoja\" type=\"hidden\" name=\"id_hoja\">\r\n");
              out.write("             <input id=\"status\" type=\"hidden\" name=\"status\">\r\n");
              out.write("            \r\n");
              out.write("\t");
              int evalDoAfterBody = _jspx_th_tiles_005fput_005f4.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_tiles_005fput_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_tiles_005fput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f4);
            return;
          }
          _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f4);
          out.write("\r\n");
          out.write("\t\r\n");
          int evalDoAfterBody = _jspx_th_tiles_005finsert_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tiles_005finsert_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.reuse(_jspx_th_tiles_005finsert_005f0);
        return;
      }
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.reuse(_jspx_th_tiles_005finsert_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction irdetalle(acc,id){\r\n");
      out.write("\t\t  \r\n");
      out.write("\t    document.forms[0].action='nuevaHojaRuta.do';\r\n");
      out.write("\t\tdocument.getElementById('accionPago').value=acc;\r\n");
      out.write("\t\tdocument.getElementById('id_hoja').value=id;\r\n");
      out.write("\t    document.forms[0].submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction ir(acc){\r\n");
      out.write("\t\tdocument.getElementById('accionPago').value=acc;\r\n");
      out.write("\t\tdocument.forms[0].submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction irCrear(acc){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t if(document.getElementById('tipohojar').value!=0){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t \tdocument.getElementById('accionPago').value=acc;\r\n");
      out.write("\t\t\t        document.forms[0].submit();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t\t   alert(\"Debe especificar el Tipo de Hoja de Ruta\");\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction agregar(acc,p){\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\tdocument.getElementById('accionPago').value=acc;\r\n");
      out.write("\t\tdocument.getElementById('pre').value=p;\r\n");
      out.write("\t    document.forms[0].submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction cambiar(acc,h,stat){\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\tdocument.getElementById('accionPago').value=acc;\r\n");
      out.write("\t\tdocument.getElementById('id_hoja').value=h;\r\n");
      out.write("\t\tdocument.getElementById('status').value=stat;\r\n");
      out.write("\t    document.forms[0].submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction buscarfechas(acc){\r\n");
      out.write("  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t if(document.getElementById('fechaInicio').value!=''){\r\n");
      out.write("\t\t\t\t\t\t if(document.getElementById('fechaFin').value!=''){\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \tdocument.getElementById('accionPago').value=acc;\r\n");
      out.write("\t\t\t\t\t\t        document.forms[0].submit();\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t }else{\r\n");
      out.write("\t\t\t\t\t\t   alert(\"Debe especificar la fecha fin\");\r\n");
      out.write("\t\t\t\t\t\t }\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t }else{\r\n");
      out.write("\t\t\t\t\t   alert(\"Debe especificar la fecha inicio\");\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction ircodigo(acc){\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\tif(document.getElementById('codigo1').value!=''){\r\n");
      out.write("\t\t\t if(document.getElementById('codigo2').value!=''){\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t    \t  document.getElementById('accionPago').value=acc;\r\n");
      out.write("\t          document.forms[0].submit();\r\n");
      out.write("\r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t          alert(\"Debe especificar el codigo de la Hoja de Ruta\");\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t     }else{\r\n");
      out.write("\t    \t alert(\"Debe especificar el codigo de la Hoja de Ruta\");\r\n");
      out.write("\t     }\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tfunction checkedAll (frm1) {\r\n");
      out.write("\t\tchecked=false;\r\n");
      out.write("\t\tvar aa= document.forms[0];\r\n");
      out.write("\r\n");
      out.write("\t\tfor (var i =0; i < aa.elements.length; i++) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t if (aa.elements[i].checked == false)\r\n");
      out.write("\t         {\r\n");
      out.write("\t          checked = true\r\n");
      out.write("\t         }\r\n");
      out.write("\t       else\r\n");
      out.write("\t         {\r\n");
      out.write("\t         checked = false\r\n");
      out.write("\t         }\r\n");
      out.write("\r\n");
      out.write("\t         \r\n");
      out.write("\t\t aa.elements[i].checked = checked;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t      }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openWinScroll2(popup_url, name, width, height) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar size = ',width=' + width + ',height=' + height;\r\n");
      out.write("\t\tvar posicion = \",left=\" + Math.round(screen.availWidth / 4) + \",top=\"\r\n");
      out.write("\t\t\t\t+ Math.round(screen.availHeight / 4);\r\n");
      out.write("\t\tvar popUp = window\r\n");
      out.write("\t\t\t\t.open(\r\n");
      out.write("\t\t\t\t\t\tpopup_url,\r\n");
      out.write("\t\t\t\t\t\tname,\r\n");
      out.write("\t\t\t\t\t\t'menubar=yes,location=no,toolbar=no,status=no,scrollbars=no,titlebar=no,directories=no,resizable=yes'\r\n");
      out.write("\t\t\t\t\t\t\t\t+ size + posicion);\r\n");
      out.write("\t\tpopUp.opener = self;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005fput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f0 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/pago/fasdemMisHojaRuta.jsp(34,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f0.setName("titulo");
    // /jsp/pago/fasdemMisHojaRuta.jsp(34,1) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f0.setDirect("true");
    int _jspx_eval_tiles_005fput_005f0 = _jspx_th_tiles_005fput_005f0.doStartTag();
    if (_jspx_eval_tiles_005fput_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_tiles_005fput_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_tiles_005fput_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_tiles_005fput_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t");
        if (_jspx_meth_bean_005fmessage_005f0(_jspx_th_tiles_005fput_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_tiles_005fput_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_tiles_005fput_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_tiles_005fput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f0);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fput_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fput_005f0);
    // /jsp/pago/fasdemMisHojaRuta.jsp(35,2) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setKey("principal.titulo");
    // /jsp/pago/fasdemMisHojaRuta.jsp(35,2) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setBundle("etiquetas");
    int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
    if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f1 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/pago/fasdemMisHojaRuta.jsp(38,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f1.setName("titulopagina");
    // /jsp/pago/fasdemMisHojaRuta.jsp(38,1) name = content type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f1.setContent("Inicio / Pagos / Mis Hojas de Ruta");
    // /jsp/pago/fasdemMisHojaRuta.jsp(38,1) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f1.setDirect("true");
    int _jspx_eval_tiles_005fput_005f1 = _jspx_th_tiles_005fput_005f1.doStartTag();
    if (_jspx_th_tiles_005fput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f1);
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f2 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f2.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/pago/fasdemMisHojaRuta.jsp(40,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f2.setName("itemsup");
    // /jsp/pago/fasdemMisHojaRuta.jsp(40,1) name = content type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f2.setContent("/jsp/comunes/items.jsp");
    int _jspx_eval_tiles_005fput_005f2 = _jspx_th_tiles_005fput_005f2.doStartTag();
    if (_jspx_th_tiles_005fput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f2);
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f3 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f3.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/pago/fasdemMisHojaRuta.jsp(41,4) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f3.setName("itemsdown");
    // /jsp/pago/fasdemMisHojaRuta.jsp(41,4) name = content type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f3.setContent(" ");
    // /jsp/pago/fasdemMisHojaRuta.jsp(41,4) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f3.setDirect("true");
    int _jspx_eval_tiles_005fput_005f3 = _jspx_th_tiles_005fput_005f3.doStartTag();
    if (_jspx_th_tiles_005fput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f3);
    return false;
  }
}
