/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.32
 * Generated at: 2014-01-22 16:18:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.pago;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ve.gob.dem.framework.recursos.*;
import java.util.Date;
import java.text.NumberFormat;
import java.util.ArrayList;
import ve.gob.dem.fasdem.bean.*;
import java.text.SimpleDateFormat;

public final class fasdemDetallePreOrden_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tlds/struts-bean.tld", Long.valueOf(1373379228980L));
    _jspx_dependants.put("/WEB-INF/tlds/struts-tiles.tld", Long.valueOf(1373379229011L));
    _jspx_dependants.put("/WEB-INF/tlds/fmt.tld", Long.valueOf(1373379229027L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1373379228996L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  tiles:insert
      org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f0 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.get(org.apache.struts.taglib.tiles.InsertTag.class);
      _jspx_th_tiles_005finsert_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsert_005f0.setParent(null);
      // /jsp/pago/fasdemDetallePreOrden.jsp(6,0) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsert_005f0.setPage("/jsp/plantilla/plantilla.jsp");
      int _jspx_eval_tiles_005finsert_005f0 = _jspx_th_tiles_005finsert_005f0.doStartTag();
      if (_jspx_eval_tiles_005finsert_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");


		Clinica proveedor=(Clinica)request.getAttribute("prov");
        DetallePreOrdenPago det =(DetallePreOrdenPago)request.getAttribute("detalle");
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
  

		 NumberFormat nf = NumberFormat.getInstance();
		 nf.setGroupingUsed(true);
		 nf.setMaximumFractionDigits(2);
	 	 String dateOut;
     	 dateOut = Utilidad.DateToString(new Date(), "dd/MM/yyyy");
     	 Double Tope=Double.parseDouble(request.getParameter("inidadTribut"))* Constantes.CantidadUnidadesPagoTimbre ;
     	 int tim;
     	 
     	Persona tit = new Persona();
     	tit.setCedula(request.getParameter("cedula"));
     	tit.setNombres(request.getParameter("nombres"));
     	tit.setApellidos(request.getParameter("apellidos"));
		

          out.write("\r\n");
          out.write("\r\n");
          out.write("\t");
          if (_jspx_meth_tiles_005fput_005f0(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t");
          if (_jspx_meth_tiles_005fput_005f1(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_tiles_005fput_005f2(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_tiles_005fput_005f3(_jspx_th_tiles_005finsert_005f0, _jspx_page_context))
            return;
          out.write('\r');
          out.write('\n');
          out.write('	');
          //  tiles:put
          org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f4 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.get(org.apache.struts.taglib.tiles.PutTag.class);
          _jspx_th_tiles_005fput_005f4.setPageContext(_jspx_page_context);
          _jspx_th_tiles_005fput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
          // /jsp/pago/fasdemDetallePreOrden.jsp(38,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_tiles_005fput_005f4.setName("cuerpo");
          // /jsp/pago/fasdemDetallePreOrden.jsp(38,1) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_tiles_005fput_005f4.setDirect("true");
          int _jspx_eval_tiles_005fput_005f4 = _jspx_th_tiles_005fput_005f4.doStartTag();
          if (_jspx_eval_tiles_005fput_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_tiles_005fput_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_tiles_005fput_005f4.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_tiles_005fput_005f4.doInitBody();
            }
            do {
              out.write("\r\n");
              out.write("\t<div style=\"overflow: visible\"></div>\r\n");
              out.write("\t\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("    <table  class=\"tabla\" width=\"600\" cellpadding=\"2\" cellspacing=\"1\" border=\"1\">\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
if(proveedor!=null && proveedor.getId()!=Constantes.ProveedorTitular && proveedor.getId()!=Constantes.ProveedorTercero){
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t <tr>\r\n");
              out.write("\t\t\t\t\t\t<td align=\"center\" colspan=\"6\" class=\"grayp\" style=\"padding-left: 20px; padding-bottom: 5px;\">\r\n");
              out.write("\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t<strong>");
              out.print(proveedor.getNombre() + " (" + proveedor.getRif() + ")" );
              out.write("</strong>\r\n");
              out.write("\t\t\t\t\t\t\t<input id=\"cadena\" type=\"hidden\" name=\"cadena\" value=");
              out.print(request.getAttribute("cadena") );
              out.write(">\r\n");
              out.write("\t\t\t\t\t\t\t<input id=\"prov_selection\" type=\"hidden\" name=\"prov_selection\" value=");
              out.print(proveedor.getId());
              out.write(">\r\n");
              out.write("\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t</td>\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t");
}else{
              out.write("\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t<tr>\r\n");
              out.write("\t\t\t\t\t\t\t\t<td align=\"center\" colspan=\"6\" class=\"grayp\" style=\"padding-left: 20px; padding-bottom: 5px;\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<div class=\"grayp\"></div>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<strong>");
              out.print(tit.getNombres()  + " " + tit.getApellidos() +  " (" + tit.getCedula() + ")" );
              out.write("</strong>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<div class=\"grayp\"></div>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<input id=\"cadena\" type=\"hidden\" name=\"cadena\" value=");
              out.print(request.getAttribute("cadena") );
              out.write(">\r\n");
              out.write("\t\t\t\t\t\t\t        <input id=\"prov_selection\" type=\"hidden\" name=\"prov_selection\" value=");
              out.print(tit.getCedula());
              out.write(">\r\n");
              out.write("\t\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\t</td>\r\n");
              out.write("\t\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
}
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> -- Numero de Pagos</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getNro_pagos()) + " Facturas");
              out.write(" </strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> -- Unidad Tributaria Aplicable</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(request.getParameter("inidadTribut"));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> -- Monto Liquidado</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getMonto_Liquidado()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Gastos Clinicos</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"> <strong>");
              out.print(nf.format(det.getGastos_Clinicos()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Honorarios Medicos</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getHonorarios_Medicos()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Farmacia</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"> <strong>");
              out.print(nf.format(det.getMedicinas()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Material Medico con IVA</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getMaterial_Medico_IVA()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Material Medico sin Iva</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getMaterial_Medico()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Servicio Odontologico</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getOdontologia()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Gastos Funerarios</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getFunerarios()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Otros Gastos</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getOtros_Gastos()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> -- Base Imponible ISLR</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\">");
              out.print(nf.format(det.getBase_imponible_isrl()));
              out.write(" Bs.</td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Monto ISLR</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getMonto_ISRL()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\r\n");
              out.write("\t \t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
if(det.getMonto_Liquidado()>=Tope){ 
              out.write("\r\n");
              out.write("\t\t\t\t");
tim=1;
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t<tr >\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t\t<td> -- Base Imponible Timbre</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\" >");
              out.print(nf.format(det.getBase_imponible_timbre()));
              out.write(" Bs.</td>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
}else{
              out.write("\r\n");
              out.write("\t\t\t\t");
tim=0;
              out.write("\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t\t<td> ---- Base Imponible Timbre</td>\r\n");
              out.write("\t\t\t\t\t\t<td align=\"right\"><strong>");
              out.print("No Aplica");
              out.write("</strong></td>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
}
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
if(det.getMonto_Liquidado()>=Tope){ 
              out.write("\r\n");
              out.write("\t\t\t\t");
tim=1;
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t<tr >\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t\t<td> ---- Monto Timbre</td>\r\n");
              out.write("\t\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getMonto_Timbre()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
}else{
              out.write("\r\n");
              out.write("\t\t\t\t");
tim=0;
              out.write("\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t\t<td> ---- Monto Timbre</td>\r\n");
              out.write("\t\t\t\t\t\t<td align=\"right\"><strong>");
              out.print("No Aplica");
              out.write("</strong></td>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
}
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<td> ---- Monto Iva</td>\r\n");
              out.write("\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getMonto_Iva()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
if(det.getMonto_Liquidado()>=Tope){ 
              out.write("\r\n");
              out.write("\t\t\t\t\t<tr >\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t\t<td> ---- Monto a Pagar</td>\r\n");
              out.write("\t\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getMonto_Liquidado()-det.getMonto_ISRL()-det.getMonto_Timbre()-det.getMonto_Iva()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
}else{
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<tr >\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t\t<td> ---- Monto a Pagar</td>\r\n");
              out.write("\t\t\t\t\t\t<td align=\"right\"><strong>");
              out.print(nf.format(det.getMonto_Liquidado()-det.getMonto_ISRL()-det.getMonto_Iva()));
              out.write(" Bs.</strong></td>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t");
}
              out.write("\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t</table>\r\n");
              out.write("\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t\r\n");
              out.write("\t\t\t\t<div style=\"border-bottom-color: #EEEEEE; border-bottom-width: thin; border-bottom-style: solid\">&nbsp;</div>\r\n");
              out.write("\t\r\n");
              out.write("\t\t\t\t<div class=\"sp5\"></div>\r\n");
              out.write("\t\t\t\t<div align=\"right\">\r\n");
              out.write("\t\t\t\t<input class=\"boton\" value=\"Crear Pre-Orden de Pago\" type=\"button\"  onclick=\"ir(3);\" />\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write(" \t\t\t\t<input id=\"anio_pre3\" type=\"hidden\" name=\"anio_pre3\" value=\"");
              out.print(request.getAttribute("anio_pre2"));
              out.write("\">\r\n");
              out.write("\t\t\t    <input id=\"accionPago\" type=\"hidden\" name=\"accionPago\" value=\"\">\r\n");
              out.write("           \t\t<input id=\"uni\" type=\"hidden\" name=\"uni\" value=");
              out.print(request.getParameter("inidadTribut"));
              out.write(">\r\n");
              out.write("           \t\t<input id=\"por\" type=\"hidden\" name=\"por\" value=");
              out.print(request.getParameter("porretiva"));
              out.write(">\r\n");
              out.write("           \t\t<input id=\"aplicTim\" type=\"hidden\" name=\"aplicTim\" value=");
              out.print(tim);
              out.write(">\r\n");
              out.write("           \t\t<input id=\"tip_select3\" type=\"hidden\" name=\"tip_select3\" value=");
              out.print(request.getAttribute("tip_select2"));
              out.write(">\r\n");
              out.write("\r\n");
              out.write("            \t<input id=\"tipopre1\" type=\"hidden\" name=\"tipopre1\" value=");
              out.print(request.getAttribute("tipoPre"));
              out.write(">\r\n");
              out.write("            \t<input id=\"tipProvSelect2\" type=\"hidden\" name=\"tipProvSelect2\" value=");
              out.print(request.getParameter("tipProvSelect1"));
              out.write(">\r\n");
              out.write("\t            <input id=\"isrl\" type=\"hidden\" name=\"isrl\" value=");
              out.print(request.getParameter("apli_isrl"));
              out.write(">\r\n");
              out.write("\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\t\r\n");
              out.write("\t");
              int evalDoAfterBody = _jspx_th_tiles_005fput_005f4.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_tiles_005fput_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_tiles_005fput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f4);
            return;
          }
          _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f4);
          out.write("\r\n");
          out.write("\t\r\n");
          int evalDoAfterBody = _jspx_th_tiles_005finsert_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tiles_005finsert_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.reuse(_jspx_th_tiles_005finsert_005f0);
        return;
      }
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fpage.reuse(_jspx_th_tiles_005finsert_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\tfunction ir(acc){\r\n");
      out.write("  \r\n");
      out.write("\t\tdocument.getElementById('accionPago').value=acc;\r\n");
      out.write("        document.forms[0].submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tfunction checkedAll (frm1) {\r\n");
      out.write("\t\tchecked=false;\r\n");
      out.write("\t\tvar aa= document.forms[0];\r\n");
      out.write("\r\n");
      out.write("\t\tfor (var i =0; i < aa.elements.length; i++) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t if (aa.elements[i].checked == false)\r\n");
      out.write("\t         {\r\n");
      out.write("\t          checked = true\r\n");
      out.write("\t         }\r\n");
      out.write("\t       else\r\n");
      out.write("\t         {\r\n");
      out.write("\t         checked = false\r\n");
      out.write("\t         }\r\n");
      out.write("\r\n");
      out.write("\t         \r\n");
      out.write("\t\t aa.elements[i].checked = checked;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t      }\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005fput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f0 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/pago/fasdemDetallePreOrden.jsp(30,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f0.setName("titulo");
    // /jsp/pago/fasdemDetallePreOrden.jsp(30,1) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f0.setDirect("true");
    int _jspx_eval_tiles_005fput_005f0 = _jspx_th_tiles_005fput_005f0.doStartTag();
    if (_jspx_eval_tiles_005fput_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_tiles_005fput_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_tiles_005fput_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_tiles_005fput_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t");
        if (_jspx_meth_bean_005fmessage_005f0(_jspx_th_tiles_005fput_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_tiles_005fput_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_tiles_005fput_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_tiles_005fput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect.reuse(_jspx_th_tiles_005fput_005f0);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fput_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fput_005f0);
    // /jsp/pago/fasdemDetallePreOrden.jsp(31,2) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setKey("principal.titulo");
    // /jsp/pago/fasdemDetallePreOrden.jsp(31,2) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setBundle("etiquetas");
    int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
    if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f1 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/pago/fasdemDetallePreOrden.jsp(34,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f1.setName("titulopagina");
    // /jsp/pago/fasdemDetallePreOrden.jsp(34,1) name = content type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f1.setContent("Inicio / Pagos / Detalle PreOrden de Pago");
    // /jsp/pago/fasdemDetallePreOrden.jsp(34,1) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f1.setDirect("true");
    int _jspx_eval_tiles_005fput_005f1 = _jspx_th_tiles_005fput_005f1.doStartTag();
    if (_jspx_th_tiles_005fput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f1);
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f2 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f2.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/pago/fasdemDetallePreOrden.jsp(36,1) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f2.setName("itemsup");
    // /jsp/pago/fasdemDetallePreOrden.jsp(36,1) name = content type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f2.setContent("/jsp/comunes/items.jsp");
    int _jspx_eval_tiles_005fput_005f2 = _jspx_th_tiles_005fput_005f2.doStartTag();
    if (_jspx_th_tiles_005fput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f2);
    return false;
  }

  private boolean _jspx_meth_tiles_005fput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsert_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:put
    org.apache.struts.taglib.tiles.PutTag _jspx_th_tiles_005fput_005f3 = (org.apache.struts.taglib.tiles.PutTag) _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.get(org.apache.struts.taglib.tiles.PutTag.class);
    _jspx_th_tiles_005fput_005f3.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsert_005f0);
    // /jsp/pago/fasdemDetallePreOrden.jsp(37,4) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f3.setName("itemsdown");
    // /jsp/pago/fasdemDetallePreOrden.jsp(37,4) name = content type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f3.setContent(" ");
    // /jsp/pago/fasdemDetallePreOrden.jsp(37,4) name = direct type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fput_005f3.setDirect("true");
    int _jspx_eval_tiles_005fput_005f3 = _jspx_th_tiles_005fput_005f3.doStartTag();
    if (_jspx_th_tiles_005fput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005fput_0026_005fname_005fdirect_005fcontent_005fnobody.reuse(_jspx_th_tiles_005fput_005f3);
    return false;
  }
}
